### ISSUE TITLE
Error wheezy 7

### ISSUE THREAD

**Issue by Owned67** [Natenom/munin-plugins#1]
Hello

./mumble return

Traceback (most recent call last):
  File "./mbl", line 68, in <module>
    users = server.getUsers()
  File "/home/serveur/murmur/Murmur.ice", line 2652, in getUsers

Murmur.ServerBootedException: exception ::Murmur::ServerBootedException
{
}

**Comment by Natenom** [comment]
> Murmur.ServerBootedException: exception ::Murmur::ServerBootedException
> {
> }

Probably the server is not running?
